export const STATUS_OPTIONS = [
    "new",
    "in-kitchen",
    "ready",
    "delivered",
    "billing-requested",
    "paid",
    "completed",
    'cancelled',
]

export const STATUS_COLORS = {
    new: "inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 inset-ring inset-ring-green-600/20",
    "in-kitchen": "inline-flex items-center rounded-md bg-pink-400/10 px-2 py-1 text-xs font-medium text-pink-400 inset-ring inset-ring-pink-400/20",
    ready: "inline-flex items-center rounded-md bg-yellow-50 px-2 py-1 text-xs font-medium text-yellow-800 inset-ring inset-ring-yellow-600/20",
    delivered: "inline-flex items-center rounded-md bg-indigo-50 px-2 py-1 text-xs font-medium text-indigo-700 inset-ring inset-ring-indigo-700/10",
    "billing-requested": "inline-flex items-center rounded-md bg-purple-50 px-2 py-1 text-xs font-medium text-purple-700 inset-ring inset-ring-purple-700/10",
    paid: "inline-flex items-center rounded-md bg-gray-50 px-2 py-1 text-xs font-medium text-gray-600 inset-ring inset-ring-gray-500/10",
    completed: "inline-flex items-center rounded-md bg-blue-50 px-2 py-1 text-xs font-medium text-blue-700 inset-ring inset-ring-blue-700/10",
    cancelled: "inline-flex items-center rounded-md bg-red-50 px-2 py-1 text-xs font-medium text-red-700 inset-ring inset-ring-red-600/10",
};



export const FOOD_CATEGORIES = [
    "Appetizers",
    "Salads",
    "Soups",
    "Main Courses",
    "Grilled",
    "Pizza",
    "Pasta",
    "Burgers",
    "Sandwiches",
    "Shawarma",
    "Fried Chicken",
    "Seafood",
    "Rice Dishes",
    "Sushi",
    "Vegetarian",
    "Vegan",
    "Desserts",
    "Ice Cream",
    "Beverages",
    "Hot Drinks",
    "Cold Drinks",
    "Smoothies",
    "Breakfast",
    "Brunch",
    "Kids Menu",
    "Special Offers",
    "Side Dishes",
    "Bakery",
    "Wraps",
    "Tacos",
    "Steaks",
    "Kebabs",
    "Mezza",
    "Arabic Food",
    "Indian Food",
    "Chinese Food",
    "Mexican Food",
    "Thai Food",
    "Japanese Food",
    "Turkish Food"
];